# Generated by Django 5.2.3 on 2025-06-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_assetclass_strategy_securities_alter_security_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="market_cap",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="security",
            name="sector",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="security",
            name="asset_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.assetclass",
            ),
        ),
        migrations.AlterField(
            model_name="security",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
