# Generated by Django 5.2.3 on 2025-06-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_security_market_cap_security_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="asset_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.assetclass",
            ),
            preserve_default=False,
        ),
    ]
