# Generated by Django 5.2.3 on 2025-06-20 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_security_asset_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="security",
            name="asset_class",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="asset_class",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="backtest",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="pricedata",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="pricedata",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="backtestresult",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="backtestresult",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="backtestresult",
            name="security",
        ),
        migrations.RemoveField(
            model_name="backtestresult",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="backtestresult",
            name="total_return",
        ),
        migrations.RemoveField(
            model_name="backtestresult",
            name="user",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="securities",
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="cumulative_return",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="max_drawdown",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="sharpe_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="trade_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="strategy",
            name="tickers",
            field=models.ManyToManyField(related_name="strategies", to="core.security"),
        ),
        migrations.AlterField(
            model_name="backtestresult",
            name="strategy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.strategy"
            ),
        ),
        migrations.AlterField(
            model_name="backtestresult",
            name="win_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pricedata",
            name="close",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="security",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="exit_rule",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="lookback_days",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.DeleteModel(
            name="AssetClass",
        ),
        migrations.DeleteModel(
            name="Trade",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
