# Generated by Django 5.2.3 on 2025-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_security_asset_class_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strategy",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Strategies"},
        ),
        migrations.AddField(
            model_name="strategy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="entry_threshold",
            field=models.FloatField(help_text="Z-score threshold for entry signal"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="exit_rule",
            field=models.CharField(
                help_text="Exit strategy rule (e.g., mean_revert, stop_loss)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="lookback_days",
            field=models.PositiveIntegerField(
                default=20, help_text="Number of days for moving average calculation"
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for your strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="tickers",
            field=models.ManyToManyField(
                blank=True, related_name="strategies", to="core.security"
            ),
        ),
    ]
