# Generated by Django 5.2.3 on 2025-06-20 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_strategy_options_strategy_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="security",
            options={"ordering": ["symbol"], "verbose_name_plural": "Securities"},
        ),
        migrations.AddField(
            model_name="security",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 6, 20, 14, 25, 42, 315422),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="security",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="security",
            name="exchange",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NYSE", "New York Stock Exchange"),
                    ("NASDAQ", "NASDAQ"),
                    ("AMEX", "American Stock Exchange"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="security",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="security",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="security",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="security",
            name="market_cap_category",
            field=models.CharField(
                choices=[
                    ("LARGE", "Large Cap (>$10B)"),
                    ("MID", "Mid Cap ($2B-$10B)"),
                    ("SMALL", "Small Cap (<$2B)"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="security",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="security",
            name="sector",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="security",
            name="symbol",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
