# Generated by Django 5.2.3 on 2025-06-20 14:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_security_options_security_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtestresult",
            name="trade_log",
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="alpha",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="annualized_return",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="avg_losing_trade",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="avg_trade_return",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="avg_winning_trade",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="backtest_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="backtest_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="benchmark_return",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="beta",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="calmar_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2015, 1, 1, 5, 0, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="losing_trades",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="sortino_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="total_trades",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="value_at_risk_95",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="volatility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="winning_trades",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("EXIT", "Exit")],
                        max_length=4,
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField(default=1)),
                ("commission", models.FloatField(default=0.0)),
                ("pnl", models.FloatField(blank=True, null=True)),
                ("cumulative_pnl", models.FloatField(blank=True, null=True)),
                ("signal_value", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backtest_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="core.backtestresult",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.security"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
